In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/Wildfire_Risk_Classification_2500.csv")
df.head()

Region_ID  Temperature  Humidity  Wind_Speed  Rainfall  Vegetation_Index  \
0          1         32.5      58.6        12.9     169.0              0.42   
1          2         29.3      64.5        12.7     104.9              0.27   
2          3         33.2      45.0         6.0     130.1              0.25   
3          4         37.6      40.8        13.3     104.0              0.27   
4          5         28.8      33.7        18.7      73.3              0.61   

   Drought_Code  Elevation  Human_Activity_Score  Fire_History Risk_Level  
0         438.0      594.0                   5.4             1        Low  
1         340.0      698.0                   6.8             1        Low  
2         217.0      589.0                   5.6             1     Medium  
3         407.0      372.0                   3.6             2     Medium  
4         302.0      273.0                   5.7             0     Medium

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Region_ID             2500 non-null   int64  
 1   Temperature           2500 non-null   float64
 2   Humidity              2500 non-null   float64
 3   Wind_Speed            2500 non-null   float64
 4   Rainfall              2500 non-null   float64
 5   Vegetation_Index      2500 non-null   float64
 6   Drought_Code          2500 non-null   float64
 7   Elevation             2500 non-null   float64
 8   Human_Activity_Score  2500 non-null   float64
 9   Fire_History          2500 non-null   int64  
 10  Risk_Level            2500 non-null   object 
dtypes: float64(8), int64(2), object(1)
memory usage: 215.0+ KB


In [ ]:
df.describe()

Region_ID  Temperature     Humidity  Wind_Speed     Rainfall  \
count  2500.00000  2500.000000  2500.000000  2500.00000  2500.000000   
mean   1250.50000    30.169400    49.661240    14.85656   100.358600   
std     721.83216     4.914893    15.140821     5.11504    39.907406   
min       1.00000    13.800000     2.300000    -1.10000   -56.900000   
25%     625.75000    26.900000    39.400000    11.40000    73.875000   
50%    1250.50000    30.100000    49.900000    14.80000   100.450000   
75%    1875.25000    33.400000    59.725000    18.40000   126.900000   
max    2500.00000    49.300000   108.900000    32.60000   235.100000   

       Vegetation_Index  Drought_Code    Elevation  Human_Activity_Score  \
count       2500.000000    2500.00000  2500.000000           2500.000000   
mean           0.547412     303.03640   503.702000              5.141120   
std            0.203863     100.37281   201.518446              2.882728   
min            0.200000      -8.00000  -227.000000              0.000000   
25%            0.370000     234.00000   367.000000              2.700000   
50%            0.540000     303.00000   504.000000              5.150000   
75%            0.730000     371.00000   640.250000              7.600000   
max            0.900000     643.00000  1396.000000             10.000000   

       Fire_History  
count   2500.000000  
mean       1.961200  
std        1.375955  
min        0.000000  
25%        1.000000  
50%        2.000000  
75%        3.000000  
max        9.000000

In [ ]:
df.isnull().sum()

Region_ID               0
Temperature             0
Humidity                0
Wind_Speed              0
Rainfall                0
Vegetation_Index        0
Drought_Code            0
Elevation               0
Human_Activity_Score    0
Fire_History            0
Risk_Level              0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Region_ID'] = label_encoder.fit_transform(df['Region_ID'])

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Risk_Level'] = label_encoder.fit_transform(df['Risk_Level'])

In [ ]:
df.head()

Region_ID  Temperature  Humidity  Wind_Speed  Rainfall  Vegetation_Index  \
0          0         32.5      58.6        12.9     169.0              0.42   
1          1         29.3      64.5        12.7     104.9              0.27   
2          2         33.2      45.0         6.0     130.1              0.25   
3          3         37.6      40.8        13.3     104.0              0.27   
4          4         28.8      33.7        18.7      73.3              0.61   

   Drought_Code  Elevation  Human_Activity_Score  Fire_History  Risk_Level  
0         438.0      594.0                   5.4             1           1  
1         340.0      698.0                   6.8             1           1  
2         217.0      589.0                   5.6             1           2  
3         407.0      372.0                   3.6             2           2  
4         302.0      273.0                   5.7             0           2

In [ ]:
df.drop(columns=["Human_Activity_Score"], inplace=True)

In [ ]:
df.head()

Region_ID  Temperature  Humidity  Wind_Speed  Rainfall  Vegetation_Index  \
0          0         32.5      58.6        12.9     169.0              0.42   
1          1         29.3      64.5        12.7     104.9              0.27   
2          2         33.2      45.0         6.0     130.1              0.25   
3          3         37.6      40.8        13.3     104.0              0.27   
4          4         28.8      33.7        18.7      73.3              0.61   

   Drought_Code  Elevation  Fire_History  Risk_Level  
0         438.0      594.0             1           1  
1         340.0      698.0             1           1  
2         217.0      589.0             1           2  
3         407.0      372.0             2           2  
4         302.0      273.0             0           2

Region_ID  Temperature  Humidity  Wind_Speed  Rainfall  Vegetation_Index  \
0          0         32.5      58.6        12.9     169.0              0.42   
1          1         29.3      64.5        12.7     104.9              0.27   
2          2         33.2      45.0         6.0     130.1              0.25   
3          3         37.6      40.8        13.3     104.0              0.27   
4          4         28.8      33.7        18.7      73.3              0.61   

   Drought_Code  Elevation  Fire_History  Risk_Level  
0         438.0      594.0             1           1  
1         340.0      698.0             1           1  
2         217.0      589.0             1           2  
3         407.0      372.0             2           2  
4         302.0      273.0             0           2

In [ ]:
df.drop(columns=["Vegetation_Index"], inplace=True)

In [ ]:
df.head()

Region_ID  Temperature  Humidity  Wind_Speed  Rainfall  Drought_Code  \
0          0         32.5      58.6        12.9     169.0         438.0   
1          1         29.3      64.5        12.7     104.9         340.0   
2          2         33.2      45.0         6.0     130.1         217.0   
3          3         37.6      40.8        13.3     104.0         407.0   
4          4         28.8      33.7        18.7      73.3         302.0   

   Elevation  Fire_History  Risk_Level  
0      594.0             1           1  
1      698.0             1           1  
2      589.0             1           2  
3      372.0             2           2  
4      273.0             0           2

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=["Risk_Level"])
y = df["Risk_Level"]

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)

LogisticRegression()

In [ ]:
ypred = model.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(ytest, ypred)
conf_matrix = confusion_matrix(ytest, ypred)
class_report = classification_report(ytest, ypred)
print("Model Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Model Accuracy: 0.856
Confusion Matrix:
 [[  0   0   2]
 [  0 311  27]
 [  2  41 117]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.88      0.92      0.90       338
           2       0.80      0.73      0.76       160

    accuracy                           0.86       500
   macro avg       0.56      0.55      0.56       500
weighted avg       0.85      0.86      0.85       500

